"""added artist model

Revision ID: be75e1b536ce
Revises: 3257b2dc7582
Create Date: 2023-05-12 16:03:09.947853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be75e1b536ce'
down_revision = '3257b2dc7582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('your_name', sa.String(length=150), nullable=True),
    sa.Column('artist_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('artist_rating', sa.Integer(), nullable=True),
    sa.Column('fav_song', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist')
    # ### end Alembic commands ###
