"""empty message

Revision ID: e4d4e2861120
Revises: 5748d6ca4019
Create Date: 2023-05-16 14:12:07.552706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d4e2861120'
down_revision = '5748d6ca4019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=150), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
